/*
    Programmers: Alvin Jay Cosare, Gabriel Lagmay, Raphael Tugasan
    Exercise 2: Atchups Bolivia COMPILER.Compiler, Date Due: February 27, 2015
*/
package INTERFACE;


import FILES.*;
import COMPILER.DATA.Variable;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.util.*;


/**
 * Description:
 *  -INTERFACE.GUI Form Class
 *
 */
public class GUI extends JFrame implements ActionListener, KeyListener, ChangeListener {
/* ArrayList that contains all opened IOL files */
    public ArrayList<IOLFile> IOLFiles;
/* GUI Menu Bar */
    public JMenuBar mbar;

    private JScrollPane jscroll;
/* File Handler class */
    private FileHandler fileHandler;
/* Represents the currently focused file in the IDE */
    private IOLFile currentFile;
/* Menu Class */
    private Menu menu;

/* Table Headers for lexeme-token and variables panes */
    private Vector LEXEMES_TOKENS_TABLE_HEADERS, VARIABLES_TABLE_HEADERS;
/* Tables Models for lexeme-token and variables tables */
    private DefaultTableModel lexemesTokensTableModel, variablesTableModel;

    public GUI()
    {
        IOLFiles = new ArrayList<IOLFile>();

        mbar = new JMenuBar();

        LEXEMES_TOKENS_TABLE_HEADERS = new Vector();
        LEXEMES_TOKENS_TABLE_HEADERS.add("Lexeme"); LEXEMES_TOKENS_TABLE_HEADERS.add("Token");

        VARIABLES_TABLE_HEADERS = new Vector();
        VARIABLES_TABLE_HEADERS.add("Name"); VARIABLES_TABLE_HEADERS.add("Type"); VARIABLES_TABLE_HEADERS.add("Initial Value");

        initComponents();

        currentFile = new IOLFile();
        fileHandler = new FileHandler(this, IOLFiles);
        menu = new Menu(this, mbar, fileHandler);
    }

    public void keyPressed(KeyEvent e){}
    public void keyReleased(KeyEvent e){}
    public void keyTyped(KeyEvent e)
    {
        currentFile.setModified(true);
        jTabbedPane.setTitleAt(currentFile.getIndex(), currentFile.getFilename() + "*");
    }

    public void actionPerformed(ActionEvent e)
    {
        if (!menu.fileTabActionListener(e)) {
            if (!menu.editTabActionListener(e)) {
                menu.runTabActionListener(e);
            }
        }
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        currentFile = IOLFiles.get(jTabbedPane.getSelectedIndex());
        menu.setCurrentFile(currentFile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane(JTabbedPane.TOP, JTabbedPane.WRAP_TAB_LAYOUT);
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();

        jTabbedPane.addChangeListener(this);

        lexemesTokensTableModel = new DefaultTableModel();
        lexemesTokensTableModel.setColumnIdentifiers(LEXEMES_TOKENS_TABLE_HEADERS);
        lexemesTokensTable = new JTable(lexemesTokensTableModel);

        variablesTableModel = new DefaultTableModel();
        variablesTableModel.setColumnIdentifiers(VARIABLES_TABLE_HEADERS);
        variablesTable = new JTable(variablesTableModel);


        jscroll = new JScrollPane();
        add(jscroll, BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setBackground(new java.awt.Color(255, 153, 51));
        jScrollPane2.setViewportView(jList1);

        lexemesTokensTable.setBackground(new java.awt.Color(153, 102, 255));
        jScrollPane3.setPreferredSize(new Dimension(100, 100));
        jScrollPane3.setViewportView(lexemesTokensTable);

        variablesTable.setBackground(new java.awt.Color(0, 204, 204));
        jScrollPane4.setViewportView(variablesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jScrollPane4))
                                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTabbedPane)
                                                .addGap(0, 0, 0)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Displays the lexemes in the editor
     * @param lexemesTokens
     */
    public void setLexemesTokens(HashMap<String, String> lexemesTokens) {
        lexemesTokensTableModel.setDataVector(null, LEXEMES_TOKENS_TABLE_HEADERS);

        Iterator iterator = lexemesTokens.entrySet().iterator(); //Format [KEY1=VALUE1, KEY2=VALUE2, ...]

        while(iterator.hasNext()) {
            lexemesTokensTableModel.addRow(iterator.next().toString().split("="));
        }


    }

    /**
     * Displays the lexemes in the editor
     * @param variables
     */
    public void setVariables(HashMap<String, Variable> variables) {
        Variable a;
        Object[] row = new Object[3];

        variablesTableModel.setDataVector(null, VARIABLES_TABLE_HEADERS);

        Iterator iterator = variables.entrySet().iterator(); //Format [KEY1=VALUE1, KEY2=VALUE2, ...]

        while(iterator.hasNext()) {
            a = variables.get(iterator.next().toString().split("=")[0]);
            row[0] = a.getName(); row[1] = a.getType(); row[2] = a.getValue();
            variablesTableModel.addRow(row);
        }
    }

    /**
     * Displays a save file dialog
     */
    private void showSaveDialog() {
        int res;
        res = JOptionPane.showConfirmDialog(this, "Do You Want to Save Changes", "File Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(res == JOptionPane.YES_OPTION)
        {
            menu.save.doClick();
        }
        else if(res == JOptionPane.CANCEL_OPTION)
        {
            return;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JTable lexemesTokensTable;
    private javax.swing.JTable variablesTable;
    private javax.swing.JList jList3;
    public javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;


    // End of variables declaration//GEN-END:variables
}