/*
    Programmers: Alvin Jay Cosare, Gabriel Lagmay, Raphael Tugasan
    Exercise 2: Atchups Bolivia Compiler, Date Due: February 27, 2015
*/

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;


/**
 * DISCLAIMER: NO OOP YET
 *
 * Description:
 *  -GUI Form Class
 *  -includes all file handling methods (temporary)
 */
public class GUI extends JFrame implements ActionListener, KeyListener
{
    private JTextArea jta;
    private JScrollPane jscroll;
    private JMenuBar mbar;

    private FileHandler fileHandler;
    private CurrentFile currentFile;
    private Menu menu;

    public GUI()
    {
        mbar = new JMenuBar();
        initComponents();
        menu = new Menu(this, mbar);
        currentFile = new CurrentFile();
        fileHandler = new FileHandler(this, currentFile);
    }

    public void keyPressed(KeyEvent e){}
    public void keyReleased(KeyEvent e){}
    public void keyTyped(KeyEvent e)
    {
        currentFile.setModified(true);
    }

    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource().equals(menu.cut) )
        {
            jta.cut();
        }
        else if(e.getSource().equals(menu.copy))
        {
            jta.copy();
        }
        else if(e.getSource().equals(menu.paste))
        {
            jta.paste();
        }
        else if(e.getSource().equals(menu.selall))
        {
            jta.selectAll();
        }
        else if(e.getSource().equals(menu.del))
        {
            jta.replaceSelection("");
        }
        else if(e.getSource().equals(menu.newFile))
        {
            currentFile.setFilename("");
            currentFile.setModified(false);
            jta.setText("");
            jta.setEnabled(true);
        }
        else if(e.getSource().equals(menu.open))
        {
            fileHandler.fileOpen();
        }
        else if(e.getSource().equals(menu.save))
        {
            fileHandler.fileSave();
        }
        else if(e.getSource().equals(menu.saveAs))
        {
            fileHandler.fileSave();
        }
        else if(e.getSource().equals(menu.exit))
        {
            fileHandler.fileExit();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jta.setFont(new Font("Consolas", Font.PLAIN, 12));
        jta.addKeyListener(this);

        jscroll = new JScrollPane(jta);
        add(jscroll, BorderLayout.CENTER );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jta.setText("No opened file");
        jta.setEnabled(false);
        jta.setColumns(20);
        jta.setRows(5);
        jScrollPane1.setViewportView(jta);

        jList1.setBackground(new java.awt.Color(255, 153, 51));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jList2.setBackground(new java.awt.Color(153, 102, 255));
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jList3.setBackground(new java.awt.Color(0, 204, 204));
        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                        .addComponent(jScrollPane4))
                                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1)
                                                .addGap(0, 0, 0)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}